[package]
name = "schrodinger_mc_1d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = { version = "0.8.4", features = ["kaleido"] }
rand = "0.8.5"
