[package]
name = "schrodinger_mc_2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
plotly = { version = "0.8.4", features = ["kaleido"] }
rand = "0.8.5"
